- hosts: "{{ server }}"
  become: yes
  tasks:
   - name: Configurando metricbeat en {{ server }}
     template:
       src: metricbeat.yml.j2
       dest: /home/bernardo/metricbeatactuator/metricbeat.yml

